repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8

-   repo: https://github.com/python-poetry/poetry
    rev: 1.2.2
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
